services:
  justwatch:
    container_name: justwatch
    image: ghcr.io/ulnanlu/justwatch:latest
    ports:
      - "43434:43434"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
